#ifndef PROTOCOL_H
#define PROTOCOL_H

/* CONSTRAINS */
#define MAX_COMMAND_SIZE 20
#define MAX_PARAMETER_SIZE 2048 //2 KiB for good measure 	

#define MIN_COMMAND_SIZE 2
#define MIN_PARAMETER_SIZE 0

/* COMMANDS TO USE WHEN COMMUNICATING */
#define PROTOCOL_DISCONNECT "DISCONNECT"
#define PROTOCOL_EXIT "EXIT"
#define PROTOCOL_GET_TIME "GETTIME"
#define PROTOCOL_IDENTIFY "IDENTIFY"
#define PROTOCOL_NMEA "NMEA"
#define PROTOCOL_PRINTCLIENTS "PRINTCLIENTS"
#define PROTOCOL_PRINTSERVER "PRINTSERVER"
#define PROTOCOL_KICK "KICK"
#define PROTOCOL_HELP "HELP"
#define PROTOCOL_PRINT_LOCATION "PRINTLOC"
#define PROTOCOL_WARMUP "WARMUP"
#define PROTOCOL_PRINTTIME "PRINTTIME"
#define PROTOCOL_DUMPDATA "DUMPDATA"
#define PROTOCOL_PRINTAVGDIFF "PRINTAVGDIFF"
#define PROTOCOL_SET_WARMUP "UPDATEWARMUP" 

/* SHORT */
#define PROTOCOL_DISCONNECT_SHORT "DC"
#define PROTOCOL_DUMPDATA_SHORT "DD"
#define PROTOCOL_IDENTIFY_SHORT "ID" 
#define PROTOCOL_PRINTCLIENTS_SHORT "PC" 
#define PROTOCOL_PRINTSERVER_SHORT "PS"  
#define PROTOCOL_PRINT_LOCATION_SHORT "PL" 
#define PROTOCOL_PRINTAVGDIFF_SHORT "PAD"
#define PROTOCOL_SET_WARMUP_SHORT "UW"

/* RESPONSES */
#define PROTOCOL_GOODBYE "Goodbye!\n"
#define PROTOCOL_OK "OK!\n\n"
#define PROTOCOL_WELCOME "Welcome to the Sensor Server!\n"

/* COMMAND CODES */
/* Used by respond() */
#define CODE_DISCONNECT 	1
#define CODE_GET_TIME 		2
#define CODE_IDENTIFY 		3
#define CODE_STORE 			4
#define CODE_NMEA 			5
#define CODE_PRINTCLIENTS 	6
#define CODE_PRINTSERVER 	7
#define CODE_KICK 			8
#define CODE_HELP 			9
#define CODE_PRINT_LOCATION 10
#define CODE_WARMUP 		11
#define CODE_PRINTTIME 		12
#define CODE_DUMPDATA		13
#define CODE_MOVED 			14 
#define CODE_PRINTAVGDIFF	15
#define CODE_SET_WARMUP		16

/* ERRORS*/
#define ERROR_ILLEGAL_COMMAND "ILLEGAL COMMAND\n"
#define ERROR_NO_ID "CLIENT NOT IDENTIFIED\n"
#define ERROR_ID_IN_USE "ID IN USE\n"
#define ERROR_ILLEGAL_MESSAGE_SIZE "ILLEGAL MESSAGE SIZE\n"
#define ERROR_WARMUP_NOT_SENSOR "WARM-UP ONLY APPLIES TO SENSORS\n"
#define ERROR_DUMPDATA_FAILED "Failed to dump data\n"

/* SIZES */
#define TIME_SIZE 9 /* SIZE OF TIME AS CHARS eg.142546.00, FROM GNRMC */

#endif /* !PROTOCOL_H */